### PR TITLE
changed the url in dsahboard

### PR DESCRIPTION
**Pull request by rajeshj11**
https://github.com/synthAI-Labs/server-OpenEdu/issues/32
made changes to fix the above issue. check below server related changes
https://github.com/synthAI-Labs/server-OpenEdu/pull/37

### CODE REVIEW

**Review by Himasnhu-AT — CHANGES_REQUESTED** [review]
instead of id, pass username in all places. the v2 thing is removed from server.
Now new api call is:
`/p/:username`

**Comment by Himasnhu-AT** [comment]
@rajeshj11 , also just a advice, kindly comment on issue you want to work with, by asking doubt if you have any, or ask maintainers to assign them to you. This way your PL will have higher chance of being merged. For example, you can see issue #5

**Comment by rajeshj11** [comment]
Thank you for the advice! I'm new to open-source contributions and
appreciate the guidance. I'll make sure to comment on the issues I'm
interested in. If there's anything specific I should keep in mind or any
other tips you have for newcomers, feel free to share. I am excited to
contribute and learn!

Thanks & Regards
Rajesh Jonnalagadda

**Review by Himasnhu-AT — APPROVED** [review]

**Comment by Himasnhu-AT** [comment]
@rajeshj11 Thanks for contribution.

and two more things you can implement to improve your contributions:

1st: before making change, like this Pull request, if their are no issues, create a issue first then make pull request.

2: Make the issue name descriptive. like instead of changed the url in dashboard, you can say 
```
updated URL of publicProfile in `/dashboard`
```

and in description say,
```
Resolving conflict introduced du to pull request 37 in server-OpenEdu, the api endpoint of public profile is changed from `/p/:profileId` to `/p/:userName`.
```
> [synthAI-Labs/server-OpenEdu#32](https://github.com/synthAI-Labs/server-OpenEdu/issues/32) made changes to fix the above issue. check below server related changes [synthAI-Labs/server-OpenEdu#37](https://github.com/synthAI-Labs/server-OpenEdu/pull/37)


By the way, this is my Discord UserName: `himanshu2005` . Ping me if you need help.

**Pull request merged**
